### ISSUE TITLE
Multi-file drag support missing when dragging patches from filesystem onto a bank

### ISSUE THREAD

**Issue by markcrosbie** [johnnyturpin-aow/zoia_lib_macOS#3]
Dragging multiple patches from the filesystem onto a bank only imports the first one.

Steps to repro:

1. Create a new bank
2. Open a folder of multiple patches, e.g. the factory euroburo patches
3. Select all patches
4. Drag the 64 patches from the finder on to the new bank
5. Only the first imported patch appears in the bank

**Comment by johnnyturpin-aow** [comment]
Fixed in beta.2
