### ISSUE TITLE
When deleting a patch from a bank also hide the right patch details pane and revert slot to empty on bank

### ISSUE THREAD

**Issue by markcrosbie** [johnnyturpin-aow/zoia_lib_macOS#4]
A slightly confusing behaviour when deleting a patch from a bank; after swiping left and clicking delete the patch details are still shown in in the right preview pane, and the delete button is still shown in the patch slot in the bank. Even though the patch has been deleted there is no visual indicator that the delete succeeded.

Suggest removing the right patch details pane and resetting the row to not display the Delete button

**Comment by johnnyturpin-aow** [comment]
Fixed in beta.2
