### ISSUE TITLE
App crashes when attempting to view Nimbus patch

### ISSUE THREAD

**Issue by jeffwhitfield** [johnnyturpin-aow/zoia_lib_macOS#5]
Hey folks!

Just downloaded the ZOIA Librarian. Pretty darn cool app so far. However, I noticed just now that it can crash at times. 

One action that crashes it consistently is when I attempt to view a patch called Nimbus (https://patchstorage.com/nimbus/). Might be something in how this patch is formatted that's causing the issue. Figure I'd post this so y'all can figure out a fix. 

Running on MacOS Monterrey 12.4 on a 2021 MacBook Pro.

I'll keep plugging away and if I find others I'll let you know. :)

**Comment by johnnyturpin-aow** [comment]
Thanks for the report... Unfortunately I am not able to reproduce this crash with this patch... strange. Does it crash for you when you select it in the Library List view or when you try to open it up in the Node viewer?

One thing you can try is to remove that patches "zbundle" folder from your library and try downloading again from the Browse view.

Easy way to find the .zbundle folder is to select the patch in the Library List view and right-click on the node view button and choose "View in Finder". It looks like /nimbus has an ID of 154261 - so it's zbundle folder is 154261.zbundle. You can just toss that in the trash and download it again using the Browse list.

Let me know if that helps or if you find any other ways to cause a crash.

**Comment by jeffwhitfield** [comment]
Huh...seems to have gone away. I guess flushing out the caches and reinstalling did the trick. Weird. :P 

Anyways...thanks for your help! Closing this one. :)
