### ISSUE TITLE
Empty UI when starting the app

### ISSUE THREAD

**Issue by maubarsom** [johnnyturpin-aow/zoia_lib_macOS#6]
Hi,

I tried downloading and running the version 1.3 (303) , but when I run the app, I get a completely blank UI like this. Am I missing something hehe? 

<img width="904" alt="Screenshot 2024-05-09 at 15 34 09" src="https://github.com/johnnyturpin-aow/zoia_lib_macOS/assets/5690589/33726297-5b80-459d-a288-ce0f805cd7e9"> 

I'm running it on a MacBook Air 15-inch, M2, 2023 with MacOS Sonoma 14.4.1 (23E224)

**Comment by johnnyturpin-aow** [comment]
Can you try simply resizing the window after it opens. This might be a new issue with Sonoma. But, I believe all it needs is a trigger to redraw the contents, and resizing the window could trigger the redraw.

**Comment by maubarsom** [comment]
Yes! that fixes it :) good enough workarond for me :) thanks for the quick reply :) Lemme know if i can help with some test

**Comment by maubarsom** [comment]
Also hmmm just realized that the patch layout algo is not working either.
Tried resizing the window but thtat didnt'fix it, and pressing the rest of the buttons hehe. Might be related 

<img width="1691" alt="Screenshot 2024-05-09 at 18 16 59" src="https://github.com/johnnyturpin-aow/zoia_lib_macOS/assets/5690589/bb079625-6148-4596-acdb-57396d84f4e7">

**Comment by johnnyturpin-aow** [comment]
It's there - its just you somehow have all the nodes panned to the far left of the window.

Pan all the nodes back to the center of the screen using option + left-click and drag to pan
Then zoom as needed.

![zoia-lib-help](https://github.com/johnnyturpin-aow/zoia_lib_macOS/assets/106853856/7dcfd73b-45f8-48a1-bfdd-d53211674fa1)

**Comment by maubarsom** [comment]
ahhh yes! it works now :) Thanks again 👍

**Comment by johnnyturpin-aow** [comment]
What I probably need to add is a button in the toolbar for re-centering and re-scaling the node display. The entire node display screen was a very quick implementation and definitely needs some more attention.

**Comment by mmairs** [comment]
Shouldn't criticize such an amazing freebie... but...
still needs resizing (on an M3/Sonoma) and I had to come here to figure it out.

**Comment by johnnyturpin-aow** [comment]
Hopefully the latest release (1.4) fixes the empty window on initial app launch issue - please provide feedback if you still see this issue.
